In [1]:
import numpy as np

In [110]:
class test_gradient():
    def __init__(self,k,alpha):
        np.random.seed(1)
        self.k=k # nombre de bras
        self.alpha=alpha # hyperparametre
        self.H = np.zeros((self.k)) # preference
        self.mu= np.random.normal(size=self.k) # récompense optimale
        
    def display(self):
        print(f"k={self.k}")
        print(f"alpha={self.alpha}")
        print(f"H(a)={self.H}")
        print(f"mu(a)={self.mu}")
        
    def one_step(self):
        # calcul les probabilités
        exp=np.exp(self.H)
        p=np.zeros((self.k))
        # votre code
        return(p)
    
    def env(self,arm):
        # renvoie la récompense
        q=np.random.normal(self.mu[arm],0.25)
        return(q)
    
    def simu(self,nbstep):
        # Simulation
        AverageReward=5 # baseline
        self.H = np.zeros((self.k)) # préférence
        indices=np.arange(self.k)
        for i in range(nbstep):
            p=self.one_step()
            # votre code
            # selection du bras en fonction des probabilités
            # calcul de la réécompense
            # mise à jour préférence du bras choisi
            # mise à jour préférence des autres bras
            arm=np.random.choice(indices,p=p)
            reward=self.env(arm)
            self.H[arm] = self.H[arm] +self.alpha*(reward-AverageReward)*(1-p[arm])
            
            for j in range(self.k):
                if j != arm:
                    self.H[j]=self.H[j]-self.alpha*(reward-AverageReward)*p[j]
            AverageReward=(AverageReward*i+reward)/(i+1)
            print(arm,reward,AverageReward)

In [111]:
s=test_gradient(10,0.1)

In [112]:
s.display()

k=10
alpha=0.1
H(a)=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
mu(a)=[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]


In [113]:
s.simu(50)

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1] -> 1.0
0 1.4093687119797282 1.4093687119797282
[0.07 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1 ] -> 1.0
5 -1.8583867895389257 -0.2245090387795987
[0.07 0.11 0.11 0.11 0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
1 -0.4706701972554612 -0.3065627582715529
[0.07 0.1  0.11 0.11 0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
9 -0.3909979328020962 -0.32767155190418873
[0.07 0.1  0.11 0.11 0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
3 -0.8904747230527094 -0.44023218613389287
[0.07 0.1  0.11 0.1  0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
9 -0.1561219282116812 -0.3928804764801909
[0.07 0.1  0.11 0.1  0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
1 -0.4783036855794347 -0.40508379206579714
[0.07 0.1  0.11 0.1  0.11 0.08 0.11 0.11 0.11 0.11] -> 1.0
5 -2.324532021631751 -0.6450148207615414
[0.07 0.1  0.11 0.1  0.11 0.06 0.11 0.11 0.11 0.11] -> 1.0
7 -0.4757212710503476 -0.6262044263491865
[0.07 0.1  0.11 0.1  0.11 0.06 0.11 0.11 0.11 0.11] -> 0.9999999999999999
8 0.03664030623087994 -0.55